### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by SergDrakus** [CraftedCat/MTProxyInstallScript#1]
When I run the script, I get an error.

**root@Telegram:** ~# touch mtpp_ins.sh && nano mtpp_ins.sh
**root@Telegram:** ~# chmod +x mtpp_ins.sh && ./mtpp_ins.sh
./mtpp_ins.sh: line 3: LBLUE=\033[1;34m: command not found
./mtpp_ins.sh: line 5: libssl-dev: command not found
./mtpp_ins.sh: line 7: cd: /opt/MTProxy/objs/bin: No such file or directory
./mtpp_ins.sh: line 8: https://core.telegram.org/getProxyConfig: No such file or directory
./mtpp_ins.sh: line 16: syntax error near unexpected token `newline'
./mtpp_ins.sh: line 16: `SyslogIdentifier=mtproxy OOMScoreAdjust=-100 [Install] WantedBy=multi-user.target" > '
**root@Telegram:** ~#

**Comment by CraftedCat** [comment]
Copy and paste body script from RAW:
https://raw.githubusercontent.com/CraftedCat/MTProxyInstallScript/master/mtproxy_install_script.sh
 and try again

**Comment by CraftedCat** [comment]
README.md updated. Steps have become easier
