### ISSUE TITLE
Please

### ISSUE THREAD

**Issue by ZarinNegah** [CraftedCat/MTProxyInstallScript#3]
hi
how are you?
Please add the following
1-Random padding
2-installed in CentOS 6
thanks

**Comment by CraftedCat** [comment]
@ZarinNegah  hi, 
1. Add dd prefix to secret (cafe...babe => ddcafe...babe) to enable this mode on client side.
Added proxy link in script end.
2. Any errors?

**Comment by ZarinNegah** [comment]
> 
> 
> @ZarinNegah hi,
> 
>     1. Add dd prefix to secret (cafe...babe => ddcafe...babe) to enable this mode on client side.
>        Added proxy link in script end.
> 
>     2. Any errors?
hi
systemd/system/
service not work to centos 6

**Comment by CraftedCat** [comment]
2. fixed, only for fresh Aruba server, with CentOS 6 x64 template. Full init.d script writing later...

**Comment by ZarinNegah** [comment]
> 
> 
>     1. fixed, only for fresh Aruba server, with CentOS 6 x64 template. Full init.d script writing later...

not work centos 6.9


Go to Telegram bot @MTProxybot, send command /newproxy
Send 188.166.2.189:64738 after answer, send secret in hex: 2a81c4c943cbcf60f71b45d8cd005326
Copy proxy TAG and write me:b74da3af020a4bda2d09c469657bfe6a
Received tag: b74da3af020a4bda2d09c469657bfe6a
Making startup script...
iptables: Setting chains to policy ACCEPT: filter          [  OK  ]
iptables: Flushing firewall rules:                         [  OK  ]
iptables: Unloading modules:                               [  OK  ]
iptables: Applying firewall rules:                         [  OK  ]
iptables: Index of insertion too big.
iptables: Saving firewall rules to /etc/sysconfig/iptables:[  OK  ]
service mtproxy does not support chkconfig
===================================

Install Complete!
Proxy Link with Random Padding: tg://proxy?server=188.166.2.189&port=64738&secret=dd2a81c4c943cbcf60f71b45d8cd005326

**Comment by ZarinNegah** [comment]
> 
> 
>     1. fixed, only for fresh Aruba server, with CentOS 6 x64 template. Full init.d script writing later...

not work centos 6.9


Go to Telegram bot @MTProxybot, send command /newproxy
Send 188.166.2.189:64738 after answer, send secret in hex: 2a81c4c943cbcf60f71b45d8cd005326
Copy proxy TAG and write me:b74da3af020a4bda2d09c469657bfe6a
Received tag: b74da3af020a4bda2d09c469657bfe6a
Making startup script...
iptables: Setting chains to policy ACCEPT: filter          [  OK  ]
iptables: Flushing firewall rules:                         [  OK  ]
iptables: Unloading modules:                               [  OK  ]
iptables: Applying firewall rules:                         [  OK  ]
iptables: Index of insertion too big.
iptables: Saving firewall rules to /etc/sysconfig/iptables:[  OK  ]
service mtproxy does not support chkconfig
===================================

Install Complete!
Proxy Link with Random Padding: tg://proxy?server=188.166.2.189&port=64738&secret=dd2a81c4c943cbcf60f71b45d8cd005326

**Comment by ZarinNegah** [comment]
> 
> 
>     1. fixed, only for fresh Aruba server, with CentOS 6 x64 template. Full init.d script writing later...

Installed right
But I did the following commands before installing it to activate

```
yum upgrade -y
yum install wget gcc gcc-c++ flex bison make bind bind-libs bind-utils epel-release iptables-services openssl openssl-devel firewalld perl quota libaio libcom_err-devel libcurl-devel tar diffutils nano dbus.x86_64 db4-devel cyrus-sasl-devel perl-ExtUtils-Embed.x86_64 cpan vim-common screen libtool perl-core zlib-devel htop git curl sudo -y
yum groupinstall "Development Tools" -y
```
and
```
iptables -I INPUT -m state --state NEW -m tcp -p tcp --dport $uport -j ACCEPT
iptables -I INPUT -m state --state NEW -m udp -p udp --dport $uport -j ACCEPT
/etc/init.d/iptables save
/etc/init.d/iptables restart
```

But after rebooting the server
The service does not work and is not automatically activated
Proxy does not work after server reset

**Comment by CraftedCat** [comment]
append in /etc/rc.df/rc.local
/etc/init.d/mtproxy

**Comment by ZarinNegah** [comment]
> 
> 
> write in /etc/rc.df/rc.local
> /etc/init.d/mtproxy

/etc/rc.df/rc.local Does not exist

I've reinstalled centos 6.9 64 bit
But the proxy does not work
tg://proxy?server=104.248.134.22&port=64738&secret=dd9f18c77ce8dcb9fcffc9d5cf53f2231a

**Comment by ZarinNegah** [comment]
edit port on line 178 ( 443 )
iptables -I INPUT 5 -m state --state NEW -m tcp -p tcp --dport 443 -j ACCEPT

**Comment by CraftedCat** [comment]
I rewrite script. try now. Edit $PORT for iptables, and add start-stop script.

**Comment by ZarinNegah** [comment]
> 
> 
> I rewrite script. try now. Edit $PORT for iptables, and add start-stop script.

do not work

```
2018-09-21 09:07:26 (234 MB/s) - “/etc/init.d/mtproxy” saved [1270/1270]

cat: /opt/MTProxy/objs/bin/options: No such file or directory
iptables: No config file.                                  [WARNING]
iptables: Index of insertion too big.
iptables: Saving firewall rules to /etc/sysconfig/iptables:[  OK  ]
===================================

Install Complete!
Proxy Link with Random Padding: tg://proxy?server=104.248.134.22&port=64738&secret=dd5d3d954d81f7ca6b727462c02b53cdf7

```

**Comment by CraftedCat** [comment]
Aruba? Centos 6 template? 
show:
iptables -L -n
ls -la /opt/MTProxy

**Comment by ZarinNegah** [comment]
no
digitalocein

IP:
104.248.134.22
user:
root
pass:
b3aa0a4b9d4dcfd6

**Comment by CraftedCat** [comment]
wait

**Comment by CraftedCat** [comment]
@ZarinNegah Go to Telegram bot @MTProxybot, send command /newproxy
Send 104.248.134.22:443 after answer, send secret in hex: 261458a9a012fbf2c6ced7720d273d84
Copy proxy TAG and write me:

**Comment by ZarinNegah** [comment]
> 
> 
> Go to Telegram bot @MTProxybot, send command /newproxy
> Send 104.248.134.22:443 after answer, send secret in hex: 261458a9a012fbf2c6ced7720d273d84
> Copy proxy TAG and write me:

no needs tag

**Comment by CraftedCat** [comment]
tg://proxy?server=104.248.134.22&port=443&secret=dd261458a9a012fbf2c6ced7720d273d84
Fixed. Service start need after echo to options :)

edthw46ryjtu71qwQQQqed

**Comment by ZarinNegah** [comment]
thanks bro
good

**Comment by ZarinNegah** [comment]
hi
I used your script on the new server ( ram 2Gb Centos 6.9 64 bit )
But I have problems again
And proxy is not active
You can check it
Thanks

tg://proxy?server=89.248.165.171&port=64738&secret=ddcfc9828f6ecd20a2193a0e5c499732f7

ip : 89.248.165.171
user : root
pass : LASvsf23rE9s

**Comment by CraftedCat** [comment]
wait

**Comment by ZarinNegah** [comment]
> 
> 
> wait

thank you
I will wait
Thanks only, you can send proxy information to Telegram
Stay private
Because it is personal use

@mortezakhodadadi

**Comment by CraftedCat** [comment]
OS: Centos 6.10
I can not help in this matter. This applies to proxy developers. I highly recommended use new Centos. You can ask here https://github.com/TelegramMessenger/MTProxy/issues. No script errors

**Comment by ZarinNegah** [comment]
hi
good time
i am add 5k secret code in mtproto....service
do not work proxy
<secret> is the secret generated at step 3. Also you can set multiple secrets: -S <secret1> -S <secret2>.
